/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DesktoPanelInternal;

import com.ps.gui.*;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class DashInternal extends javax.swing.JFrame {

    /**
     * Creates new form DashInternal
     */
    public DashInternal() {
        initComponents();
        
    }
    
   
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubox = new javax.swing.JPanel();
        generalDiary1 = new javax.swing.JLabel();
        policeInfo1 = new javax.swing.JLabel();
        dash1 = new javax.swing.JLabel();
        userName19 = new javax.swing.JLabel();
        activity1 = new javax.swing.JLabel();
        logOut1 = new javax.swing.JLabel();
        criminalInfo1 = new javax.swing.JLabel();
        addNewAdmin1 = new javax.swing.JLabel();
        caseInfo1 = new javax.swing.JLabel();
        others4 = new javax.swing.JLabel();
        others3 = new javax.swing.JLabel();
        editProfile1 = new javax.swing.JLabel();
        personalInfo1 = new javax.swing.JLabel();
        others5 = new javax.swing.JLabel();
        dumInfo1 = new javax.swing.JLabel();
        comInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titlebar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        deskTopPane = new javax.swing.JDesktopPane();
        policeboard1 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        addPol4 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menubox.setBackground(new java.awt.Color(51, 51, 51));
        menubox.setPreferredSize(new java.awt.Dimension(250, 650));
        menubox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generalDiary1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generalDiary1.setForeground(new java.awt.Color(255, 255, 255));
        generalDiary1.setText("General Diary");
        generalDiary1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalDiary1MouseClicked(evt);
            }
        });
        menubox.add(generalDiary1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 160, 50));

        policeInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        policeInfo1.setForeground(new java.awt.Color(255, 255, 255));
        policeInfo1.setText("Police Information");
        policeInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeInfo1MouseClicked(evt);
            }
        });
        menubox.add(policeInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 50));

        dash1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dash1.setForeground(new java.awt.Color(255, 255, 255));
        dash1.setText("Dashboard");
        dash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dash1MouseExited(evt);
            }
        });
        menubox.add(dash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 50));

        userName19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName19.setForeground(new java.awt.Color(255, 255, 255));
        userName19.setText("MinhajulIslam");
        menubox.add(userName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        activity1.setForeground(new java.awt.Color(51, 255, 0));
        activity1.setText("Online");
        menubox.add(activity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        logOut1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logOut1.setForeground(new java.awt.Color(255, 255, 255));
        logOut1.setText("Log Out");
        menubox.add(logOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 60, -1));

        criminalInfo1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        criminalInfo1.setForeground(new java.awt.Color(255, 255, 255));
        criminalInfo1.setText("Criminal Information");
        criminalInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criminalInfo1MouseClicked(evt);
            }
        });
        menubox.add(criminalInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 50));

        addNewAdmin1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addNewAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        addNewAdmin1.setText("Add New Admin");
        menubox.add(addNewAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 100, -1));

        caseInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        caseInfo1.setForeground(new java.awt.Color(255, 255, 255));
        caseInfo1.setText("Case Information");
        caseInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseInfo1MouseClicked(evt);
            }
        });
        menubox.add(caseInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 50));

        others4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others4.setForeground(new java.awt.Color(255, 255, 255));
        others4.setText("Arms & Ammos");
        others4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others4MouseClicked(evt);
            }
        });
        menubox.add(others4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 160, 50));

        others3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others3.setForeground(new java.awt.Color(255, 255, 255));
        others3.setText("Others");
        menubox.add(others3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 160, 50));

        editProfile1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editProfile1.setForeground(new java.awt.Color(255, 255, 255));
        editProfile1.setText("Edit Your Profile");
        menubox.add(editProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 110, -1));

        personalInfo1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        personalInfo1.setForeground(new java.awt.Color(153, 153, 153));
        personalInfo1.setText("Personal Information");
        menubox.add(personalInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 150, -1));

        others5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        others5.setForeground(new java.awt.Color(255, 255, 255));
        others5.setText("Vehicle Information");
        others5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                others5MouseClicked(evt);
            }
        });
        others5.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                others5CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        menubox.add(others5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, 50));

        dumInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dumInfo1.setForeground(new java.awt.Color(255, 255, 255));
        dumInfo1.setText("Dumpyard");
        dumInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dumInfo1MouseClicked(evt);
            }
        });
        menubox.add(dumInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 160, 50));

        comInfo.setBackground(new java.awt.Color(0, 51, 51));
        comInfo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        comInfo.setForeground(new java.awt.Color(255, 255, 255));
        comInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comInfo.setText("Police Page");
        comInfo.setOpaque(true);
        menubox.add(comInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 50));

        jLabel1.setText("jLabel1");
        menubox.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, -1, -1));

        getContentPane().add(menubox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 700));

        titlebar.setBackground(new java.awt.Color(0, 51, 51));
        titlebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Police Station Management System");
        titlebar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel142.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(153, 153, 153));
        jLabel142.setText("Version 1.0");
        jLabel142.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        titlebar.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 234, 30));

        getContentPane().add(titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1000, 50));

        policeboard1.setBackground(new java.awt.Color(204, 204, 255));
        policeboard1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton38.setText("Create Role");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        policeboard1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, 40));

        addPol4.setText("Add New Police");
        addPol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPol4ActionPerformed(evt);
            }
        });
        policeboard1.add(addPol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 40));

        jButton39.setText("Find Police");
        jButton39.setActionCommand("Close Case");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        policeboard1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 130, 40));

        jButton40.setText("Solved/Closed Case");
        jButton40.setActionCommand("Close Case");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        policeboard1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 130, 40));

        jButton41.setText("Closed Case");
        jButton41.setActionCommand("Close Case");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        policeboard1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 130, 40));

        jButton42.setText("Police Information Update");
        jButton42.setActionCommand("Close Case");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        policeboard1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 130, 40));

        javax.swing.GroupLayout deskTopPaneLayout = new javax.swing.GroupLayout(deskTopPane);
        deskTopPane.setLayout(deskTopPaneLayout);
        deskTopPaneLayout.setHorizontalGroup(
            deskTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(policeboard1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        deskTopPaneLayout.setVerticalGroup(
            deskTopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(policeboard1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        deskTopPane.setLayer(policeboard1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(deskTopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 1000, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalDiary1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalDiary1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generalDiary1MouseClicked

    private void policeInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeInfo1MouseClicked
        // TODO add your handling code here:
        
        policeboard pb = new policeboard();
        deskTopPane.removeAll();
        deskTopPane.add(pb).setVisible(true);

        //        caseborad.setVisible(false);
        //        criminalborad.setVisible(false);
        //        gdboard.setVisible(false);
        //        dumpboard.setVisible(false);
        //        vehicleboard.setVisible(false);
        //        armsboard.setVisible(false);
        //        dashboard.setVisible(false);
        //        policeboard.setVisible(true);
    }//GEN-LAST:event_policeInfo1MouseClicked

    private void dash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseClicked
        // TODO add your handling code here:
        
        deskTopPane.removeAll();
        deskTopPane.add(policeboard1).setVisible(true);
        
        
        

    }//GEN-LAST:event_dash1MouseClicked

    private void dash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseEntered

    private void dash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dash1MouseExited

    private void criminalInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criminalInfo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_criminalInfo1MouseClicked

    private void caseInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caseInfo1MouseClicked

    }//GEN-LAST:event_caseInfo1MouseClicked

    private void others4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others4MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_others4MouseClicked

    private void others5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_others5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_others5MouseClicked

    private void others5CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_others5CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_others5CaretPositionChanged

    private void dumInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dumInfo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dumInfo1MouseClicked

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void addPol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPol4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPol4ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashInternal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activity1;
    private javax.swing.JLabel addNewAdmin1;
    private javax.swing.JButton addPol4;
    private javax.swing.JLabel caseInfo1;
    private javax.swing.JLabel comInfo;
    private javax.swing.JLabel criminalInfo1;
    private javax.swing.JLabel dash1;
    private javax.swing.JDesktopPane deskTopPane;
    private javax.swing.JLabel dumInfo1;
    private javax.swing.JLabel editProfile1;
    private javax.swing.JLabel generalDiary1;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel logOut1;
    private javax.swing.JPanel menubox;
    private javax.swing.JLabel others3;
    private javax.swing.JLabel others4;
    private javax.swing.JLabel others5;
    private javax.swing.JLabel personalInfo1;
    private javax.swing.JLabel policeInfo1;
    private javax.swing.JPanel policeboard1;
    private javax.swing.JPanel titlebar;
    private javax.swing.JLabel userName19;
    // End of variables declaration//GEN-END:variables

    private void setBorder(Border createEmptyBorder) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
